SELECT PRODUCT_CODE,sum(PRICE*OFFLINE_SALE.SALES_AMOUNT) as 'SALES'
    from PRODUCT,OFFLINE_SALE
    where PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
    group by PRODUCT.PRODUCT_ID
    order by sum(PRICE*OFFLINE_SALE.SALES_AMOUNT)  desc , PRODUCT.PRODUCT_CODE;