SELECT TITLE,USED_GOODS_BOARD.BOARD_ID,REPLY_ID,USED_GOODS_REPLY.WRITER_ID,
    USED_GOODS_REPLY.CONTENTS,
    DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE,'%Y-%m-%d') as 'CREATED_DATE'
    from USED_GOODS_BOARD,USED_GOODS_REPLY
    where USED_GOODS_BOARD.CREATED_DATE Like '2022-10%' and
    USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
    order by USED_GOODS_REPLY.CREATED_DATE, TITLE;